### ISSUE TITLE
Logs for Stanford Tagger

### ISSUE THREAD

**Issue by smendez-hi** [SIMPATICOProject/SimpaticoTAEServer#3]
Where can we see the logs for the Spanish Stanford tagger? Sometimes the process crashes and we don't know why. And that causes the Lexical Simplification Server to stop as well.
Thanks.

**Comment by ghpaetzold** [comment]
Hi Samuel,


If you ran it using nohup, try looking at the "nohup.out" file. Otherwise, you can launch the Stanford Tagger using a "1> output.txt 2> errorlog.txt" at the end of the command so that the stderror stream is redirected to "errorlog.txt".


Regards,

_______________________________

Gustavo Henrique Paetzold
Research Associate in Text Adaptation
University of Sheffield
________________________________
De: Samuel Méndez <notifications@github.com>
Enviado: quarta-feira, 18 de outubro de 2017 08:53:13
Para: SIMPATICOProject/SimpaticoTAEServer
Cc: Subscribed
Assunto: [SIMPATICOProject/SimpaticoTAEServer] Logs for Stanford Tagger (#3)


Where can we see the logs for the Spanish Stanford tagger? Sometimes the process crashes and we don't know why. And that causes the Lexical Simplification Server to stop as well.
Thanks.

**Comment by smendez-hi** [comment]
Ok, we will try the second option because we don't use nohup for it. Thanks!
