### ISSUE TITLE
python dependencies issues

### ISSUE THREAD

**Issue by mirkoperillo** [SIMPATICOProject/SimpaticoTAEServer#6]
README misses some python dependencies

To run `Run_TCP_Lexical_Simplifier_Server` **tensorflow** is required

To run `Run_TCP_Syntactic_Simplifier_Server` **pexpect** and **unidecode** are required.

There are some version problems:
* The last tensorflow version (1.8.0) broke the execution of the application. All works using the 1.3.0 version
* The last version of nltk(3.2.5) broke your source code in the import definition of StandfordTokenizer

If think it could be more dev friendly if you can provide a requirements.txt with pip freeze to have a complete list of dependencies with the correct version to have a working installation.

**Comment by ghpaetzold** [comment]
Hello,


It took me a while because of the job transition I'm going through, but I managed to add a requirements.txt file to the project :)


It contains the version of all python libraries being used at our local server.


Regards,


_______________________________

Gustavo Henrique Paetzold
Research Associate in Text Adaptation
University of Sheffield
________________________________
De: mirko <notifications@github.com>
Enviado: quarta-feira, 2 de maio de 2018 10:03:10
Para: SIMPATICOProject/SimpaticoTAEServer
Cc: Subscribed
Assunto: [SIMPATICOProject/SimpaticoTAEServer] python dependencies issues (#6)


README misses some python dependencies

To run Run_TCP_Lexical_Simplifier_Server tensorflow is required

To run Run_TCP_Syntactic_Simplifier_Server pexpect and unidecode are required.

There are some version problems:

  *   The last tensorflow version (1.8.0) broke the execution of the application. All works using the 1.3.0 version
  *   The last version of nltk(3.2.5) broke your source code in the import definition of StandfordTokenizer

If think it could be more dev friendly if you can provide a requirements.txt with pip freeze to have a complete list of dependencies with the correct version to have a working installation.
